### ISSUE TITLE
Feat: [UI] 사용자 UI 구현

### ISSUE THREAD

**Issue by daron135** [66yurimi99/Z-ERO#18]
## Description  
자동차 주행 환경에 대한 사용자 UI를 구현.
<br>

## Todo  
- [x] 각각의 Thread 생성
  - DMS (Live video from camera)
  - RC Car (Live video from camera)
  - Processing (Segmentation : Lane / Object Detection : Car)
- [x] Mutex 사용하여 Thread 간 동기화
- [x] 기능에 맞는 디자인 구현
<br>

## Etc
기타 사항 또는 참고가 될 예시 자료, 링크를 추가하세요.
