### ISSUE TITLE
Feat: [FCA] Object Detection을 위한 AI Custom Model 트레이닝 환경 설정

### ISSUE THREAD

**Issue by YuNayeong** [66yurimi99/Z-ERO#19]
## Description  
Object Detection을 위한 AI Custom Model 트레이닝을 위한 환경 설정입니다.
<br>

## Todo  

- [x] dataset 구현을 위한 이미지 촬영 및 라벨링 작업
  - CVAT 툴을 이용한 Annotation 작업

- [x] Yolo 모델 사용을 위해 Darknet 프레임워크가 사용하는 label dataset으로 포맷 변경
  - 프로젝트 'convert2Yolo'를 이용해 coco -> yolo DarkNet 포맷 변경
```
# Install convert2Yolo
$ git clone https://github.com/ssaru/convert2Yolo
$ cd convert2Yolo
$ pip install -r requirments.txt

# Convert format
$ python example.py \
--datasets COCO --img_path [이미지 파일 경로] \
--label [변환 전 label이 정의된 파일 경로(.json)] \
--convert_output_path [변환 후 라벨이 정의된 파일 경로] \
--img_type [이미지 포맷('.jpg')] \
--cls_list_file [클래스 정의 파일 path]
```

- [x] Yolo 모델 트레이닝을 위한 오픈소스 설치
  - 오픈 소스 'Ultralytics'
```
$ git clone https://github.com/ultralytics/yolov5
$ cd yolov5
$ pip install -r requirments.txt
```

- [x] Yolo 모델 트레이닝을 위한 dataset 설정
  - dataset 분리 (train : val : test = 7 : 2 : 1)
  - 디렉토리 구조 
    <img width="147" alt="스크린샷 2023-11-22 오후 8 51 09" src="https://github.com/66yurimi99/Z-ERO/assets/147594641/9486c2a2-a25b-4241-a1df-7ad3025faed4">
  - dataset의 정보를 담고 있는 .yaml 파일 생성

<br>

## 산출물

- Dataset Annotation
  - export dataset (format : COCO 1.0)
  : [coco 1.0.zip](https://github.com/66yurimi99/Z-ERO/files/13438420/coco.1.0.zip)

- Change Label Format (coco -> yolo Darknet)
  - Yolo format
  : [yolo.zip](https://github.com/66yurimi99/Z-ERO/files/13438649/yolo.zip)

- Dataset settings 
  - .yaml file
  : [custom.yaml.zip](https://github.com/66yurimi99/Z-ERO/files/13439294/custom.yaml.zip)

<br>

## 참고자료

- CVAT
  : https://app.cvat.ai/tasks/381803/jobs/422067

- convert2Yolo 
   GitHub : https://github.com/ssaru/convert2Yolo 
   Study : https://deepbaksuvision.github.io/Modu_ObjectDetection/posts/02_02_Convert2Yolo.html
- Ultralytics
  GitHub : https://github.com/ultralytics/yolov5
