### ISSUE TITLE
Feat: [UI] Linux 환경 Setting

### ISSUE THREAD

**Issue by daron135** [66yurimi99/Z-ERO#22]
## Description  
Linux 환경에서 적용될 수 있도록 환경 최적화
<br>

## Todo  
- [x] Window에서 구현된 UI를 Linux 환경에서 가능하게 setting
- [x] 현재 절대경로로 설정되어 있는데 상대경로로 가능하게 setting
- [x] 차량 번호 등록하고 서버에 전송하는 기능 추가
- [x] 구현된 코드 최적화
<br>
