### ISSUE TITLE
Feat: [LCA] Lane Detection을 위한 Instance segmentation 트레이닝

### ISSUE THREAD

**Issue by ParkYoungMoon** [66yurimi99/Z-ERO#27]
## Description  
Lane segmentation을 위한 AI Model training
<br>

## Todo  
- [x] Instance segmentation을 위한 Dataset 구축
  - CVAT을 활용하여 Annotation 진행

- [x] Custom model Training

- [x] Instance segmentation model 별 성능 비교
  - MaskRCNN-ResNet50
  - MaskRCNN-EfficientNetB2B

- [x] 최종 모델 선정
  - 각 Instance segmentation model 성능에 따른 최종 Custom model 선정

<br>

## Etc
기타 사항 또는 참고가 될 예시 자료, 링크를 추가하세요.

**Comment by jis0202** [comment]
모델 테스트용 코드 입니다
```python
import logging as log
import sys

import cv2
import numpy as np
import openvino as ov

from openvino.inference_engine import IECore

# 모델 파일 경로
model_xml = '../model/model.xml'
model_bin = '../model/model.bin'  # .bin 파일도 함께 있는 경우
image_path = "/home/isjeong/Downloads/test.jpg"

# Inference Engine 초기화
core = ov.runtime.Core()
ie = IECore()

image = cv2.imread(image_path)
images = cv2.resize(image, (416, 416))

# Change color order if needed (BGR to RGB or vice versa)
image = images[..., ::-1]

# Change data layout to HWC
image = image.transpose((2, 0, 1))

input_tensor = np.expand_dims(image, 0)

net = ie.read_network(model=model_xml, weights=model_bin)
input_layer_name = next(iter(net.input_info))
input_shape = net.input_info[input_layer_name].input_data.shape
input_shape[0] = 1
net.reshape({input_layer_name: input_shape})

# Executable Network 생성
exec_net = ie.load_network(network=net, device_name='CPU', num_requests=1)

results = exec_net.infer(inputs={input_layer_name: image})

img_crop = images[174:289,173:258]

img_crop = cv2.resize(img_crop, (224, 224))

#cv2.rectangle(images, (173, 174), (258, 289), (0, 0, 255), 2)
cv2.imwrite("OUTPUT/boundingbox.jpg", images)
cv2.imwrite("OUTPUT/roi1.jpg", img_crop)
print(results['boxes'][0][0])

'''
image = cv2.imread(image_path)
image = cv2.resize(image, (416, 416))
input_tensor = np.expand_dims(image, 0)

model = core.read_model(model_xml, model_bin)

ppp = ov.preprocess.PrePostProcessor(model)

ppp.input().tensor().set_shape([1, 3, 416, 416])

model = ppp.build()

compiled_model = core.compile_model(model, "CPU")

results = compiled_model.infer_new_request(input_tensor)

print(results)
```
