### ISSUE TITLE
Feat: [LCA] Lane Segmentation의 따른 RC카 주행 알고리즘 구현

### ISSUE THREAD

**Issue by ParkYoungMoon** [66yurimi99/Z-ERO#30]
## Description  
Lane Segmentation의 따른 RC카 주행 알고리즘 구현
<br>

## Todo  
- [x] Raspberry PI로 부터 Frame 데이터 수신

- [x] Start (시동) 데이터 수신   

- [x] Frame 내 Instance segmentation 적용

- [x] 적용된 Instance segmentation의 따른 주행 알고리즘 (직선, 코너) 구현

<br>

## Etc
기타 사항 또는 참고가 될 예시 자료, 링크를 추가하세요.
