### ISSUE TITLE
Feat: [LCA] LCA & FCA 통합

### ISSUE THREAD

**Issue by ParkYoungMoon** [66yurimi99/Z-ERO#53]
## Description  
Lane detection인 LCA, Object detection인 FCA 통합
<br>

## Todo  
- [x] LCA & FCA 통합
- [x] LCA & FCA 통합 테스트
- [ ] Frame 데이터 전송
- [ ] 모듈화 
<br>

## Etc
기타 사항 또는 참고가 될 예시 자료, 링크를 추가하세요.
